use crate::value::Value;

pub enum Instruction {
    Push(Value),
    PushStr(String),
    PushSpace,
    PushBool(bool),
    Pop,
    Add,
    Sub,
    Mul,
    Div,
    Store(String),
    Load(String),
    Drop(String),
    Jump(usize),
    Print,
    Println,
    Read,
    JumpIf(Value, usize),
    ReadF(String),
    WriteF(String, String),
    RemoveF(String),
    CreateDir(String),
    RemoveDir(String),
    StoI,
    StoF,
    ItoF,
    ItoS,
    FtoI,
    FtoS,
    Exit,
}
